### ISSUE TITLE
feature request: options for 'delimiter' and 'capitalize'

### ISSUE THREAD

**Issue by vimtoe** [norskeld/diceware#1]
Hi! This is great - thank you! a couple suggestions...
- Some places do not allow whitespace in passwords, with a 'delimiter' option we could pick something like `-` or `_`, or better yet - none at all! Which leads me to...
- An option to capitalize the first letter of each word option would mean we would not need a delimiter at all!

With both of these implemented it would actually be safer too; whilst it does not add any more entropy - it does protects against entropy loss, for that reason, a password like `OneTwoThreeFour` is better than one like `one two three four`, but most importantly - it is accepted everywhere 👍

**Comment by norskeld** [comment]
Hi and thanks for the suggestions! Sounds pretty reasonable, I will ~try to~ implement them on Sunday.

**Comment by norskeld** [comment]
Done! See the PR #2.

**Comment by vimtoe** [comment]
**Thank you!**
I love the 'presets' idea too!
And you even added an entropy calculator! 🔥 
This is now **perfect!** - all the features you'd ever need 🤘
